#!/usr/bin/env python3
"""Flatten src/*.scad into one file for MakerWorld's Parametric Model Maker.

PMM does not resolve local include trees, so the published model has to be a
single .scad. Development happens in src/, this produces dist/.
"""
import pathlib, datetime, re

ROOT = pathlib.Path(__file__).parent
SRC, DIST = ROOT / "src", ROOT / "dist"
ORDER = ["00_header", "10_hubs", "20_treads", "30_core", "40_joint",
         "60_test_parts", "50_output"]

PARAM_START = re.compile(r"^/\* \[", re.M)
CODE_START = re.compile(r"^(module|function)\s", re.M)


def split_params(text):
    """Return (parameter block, everything else) for one source file."""
    m = PARAM_START.search(text)
    if not m:
        return "", text
    c = CODE_START.search(text, m.start())
    end = c.start() if c else len(text)
    return text[m.start():end], text[:m.start()] + text[end:]


def main():
    DIST.mkdir(exist_ok=True)
    parts = []
    for name in ORDER:
        f = SRC / f"{name}.scad"
        if not f.exists():
            raise SystemExit(f"missing {f}")
        parts.append(f.read_text())
    # The OpenSCAD customizer, and MakerWorld with it, only picks up
    # parameters declared before the first module or function in the file.
    # Groups that live next to the code they belong to would silently
    # vanish from the UI, so hoist every parameter block to the top.
    hoisted, rest = [], []
    for name, text in zip(ORDER, parts):
        block, remainder = split_params(text)
        if block:
            hoisted.append(f"// ---- from src/{name}.scad ----\n{block.rstrip()}")
        rest.append(remainder)
    body = "\n\n".join(hoisted) + "\n\n" + "\n\n".join(rest)

    stamp = datetime.date.today().isoformat()
    banner = (f"// Generated by build.py on {stamp} from src/. Do not edit here,\n"
              f"// edit src/ and rebuild.\n\n")

    # MakerWorld calls the plate modules itself
    pmm = banner + body.replace("standalone = true;", "standalone = false;")
    (DIST / "mower_wheel_pmm.scad").write_text(pmm)

    # desktop copy, renders on open
    (DIST / "mower_wheel.scad").write_text(banner + body)

    n = len(pmm.splitlines())
    print(f"dist/mower_wheel_pmm.scad  {n} lines, {len(pmm)/1024:.1f} KB")
    print(f"dist/mower_wheel.scad      desktop version")
    groups = re.findall(r"/\* \[([^\]]+)\] \*/", body)
    print("customizer groups:", ", ".join(g for g in groups if g != "Hidden"))

if __name__ == "__main__":
    main()
